/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */
import type { AutoPostEditedAt } from './autoPostEditedAt';
import type { AutoPostOriginalContentHash } from './autoPostOriginalContentHash';
import type { Deal } from './deal';

export interface AutoPost {
  id: string;
  dealId: string;
  deal: Deal;
  telegramMessageId: string;
  verified: boolean;
  /** @nullable */
  verifiedAt: string | null;
  /** @nullable */
  postedAt: string | null;
  /** @nullable */
  verificationDeadline: string | null;
  /** @nullable */
  originalContentHash: AutoPostOriginalContentHash;
  edited: boolean;
  /** @nullable */
  editedAt: AutoPostEditedAt;
}
