/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */
import type { Campaign } from './campaign';
import type { CampaignFilterType } from './campaignFilterType';

export interface CampaignFilter {
  id: string;
  campaignId: string;
  campaign: Campaign;
  type: CampaignFilterType;
  value: string;
}
