/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */
import type { CampaignFilter } from './campaignFilter';
import type { CampaignStatus } from './campaignStatus';
import type { User } from './user';

export interface Campaign {
  id: string;
  createdAt: string;
  /** Advertiser telegram user ID */
  advertiserTelegramId: string;
  advertiser: User;
  budgetTon: number;
  brief: string;
  filters: CampaignFilter[];
  status: CampaignStatus;
}
