/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */
import type { Channel } from './channel';

export interface ChannelListing {
  id: string;
  createdAt: string;
  channelId: string;
  channel: Channel;
  priceTon: number;
  formatDescription: string;
  active: boolean;
}
