/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';

export interface Channel {
  id: string;
  createdAt: string;
  /** Telegram channel ID */
  telegramChannelId: string;
  title: string;
  /** @nullable */
  username: string | null;
  /** @nullable */
  description: string | null;
  /** @nullable */
  photoUrl: string | null;
  /** Owner telegram user ID */
  ownerTelegramId: string;
  owner: User;
  botIsAdmin: boolean;
  verified: boolean;
  /** @nullable */
  subscribers: number | null;
  /** @nullable */
  avgViews: number | null;
}
