/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */

export type CreateChannelManagerDtoRightsItem = typeof CreateChannelManagerDtoRightsItem[keyof typeof CreateChannelManagerDtoRightsItem];


export const CreateChannelManagerDtoRightsItem = {
  post: 'post',
  finance: 'finance',
  edit: 'edit',
} as const;
