/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */

export interface CreateWithdrawalDto {
  /** Amount in TON, decimal string (example: 1.5) */
  amountTon: string;
  /** Destination wallet address. If omitted, user profile address is used. */
  toAddress?: string;
}
