/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */
import type { CreateCampaignFilterDtoType } from './createCampaignFilterDtoType';

export interface CreateCampaignFilterDto {
  type: CreateCampaignFilterDtoType;
  /** Filter value as string (number/string by type) */
  value: string;
}
