/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */

export interface CreateDealFromListingDto {
  /** Listing UUID */
  listingId: string;
  /** Advertiser brief and requirements */
  brief: string;
  /** Proposed publish date */
  publishAt?: string;
}
