/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */

export type CreateCampaignFilterDtoType = typeof CreateCampaignFilterDtoType[keyof typeof CreateCampaignFilterDtoType];


export const CreateCampaignFilterDtoType = {
  minSubscribers: 'minSubscribers',
  minAvgViews: 'minAvgViews',
  language: 'language',
} as const;
