/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */
import type { CreateCampaignFilterDto } from './createCampaignFilterDto';

export interface CreateCampaignDto {
  /** Total budget in TON */
  budgetTon: number;
  /** Campaign brief / ad copy requirements */
  brief: string;
  /** Filter criteria for target channels */
  filters?: CreateCampaignFilterDto[];
}
