/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */

export interface CreateDealFromCampaignDto {
  /** Campaign UUID */
  campaignId: string;
  /** Channel UUID to run the ad in */
  channelId: string;
  /** Price proposed by channel owner in TON */
  priceTon: number;
  /** Proposed publish date */
  publishAt?: string;
}
