/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type DealCounterpartyDtoUsername = { [key: string]: unknown } | null;
