/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */
import type { Deal } from './deal';

export interface DealMessage {
  id: string;
  createdAt: string;
  dealId: string;
  deal: Deal;
  senderTelegramId: number;
  recipientTelegramId: number;
  text: string;
}
