/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */
import type { DealCounterpartyDtoPhotoUrl } from './dealCounterpartyDtoPhotoUrl';
import type { DealCounterpartyDtoUsername } from './dealCounterpartyDtoUsername';

export interface DealCounterpartyDto {
  /** Telegram user ID */
  telegramId: string;
  /** @nullable */
  username: DealCounterpartyDtoUsername;
  /** @nullable */
  photoUrl: DealCounterpartyDtoPhotoUrl;
}
