/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */

export type DealDetailDtoSourceType = typeof DealDetailDtoSourceType[keyof typeof DealDetailDtoSourceType];


export const DealDetailDtoSourceType = {
  listing: 'listing',
  campaign: 'campaign',
} as const;
