/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */
import type { AutoPost } from './autoPost';
import type { Campaign } from './campaign';
import type { Channel } from './channel';
import type { ChannelListing } from './channelListing';
import type { DealCounterpartyDto } from './dealCounterpartyDto';
import type { DealDetailDtoSourceType } from './dealDetailDtoSourceType';
import type { DealDetailDtoStatus } from './dealDetailDtoStatus';
import type { User } from './user';

export interface DealDetailDto {
  id: string;
  createdAt: string;
  channel: Channel;
  /** @nullable */
  channelId: string | null;
  /** Advertiser telegram user ID */
  advertiserTelegramId: string;
  advertiser: User;
  /** Channel owner telegram user ID */
  channelOwnerTelegramId: string;
  channelOwner: User;
  priceTon: number;
  /** @nullable */
  brief: string | null;
  sourceType: DealDetailDtoSourceType;
  /** @nullable */
  escrowAddress: string | null;
  status: DealDetailDtoStatus;
  /** @nullable */
  publishAt: string | null;
  /** @nullable */
  listingId: string | null;
  listing: ChannelListing | null;
  /** @nullable */
  campaignId: string | null;
  campaign: Campaign | null;
  /** @nullable */
  statusChangedAt: string | null;
  /** @nullable */
  paymentDeadline: string | null;
  autoPost: AutoPost | null;
  counterparty: DealCounterpartyDto | null;
}
