/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */
import type { EscrowInfoDtoStatus } from './escrowInfoDtoStatus';

export interface EscrowInfoDto {
  id: string;
  dealId: string;
  tonAddress: string;
  amountTon: number;
  status: EscrowInfoDtoStatus;
}
