/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */

export type EscrowInfoDtoStatus = typeof EscrowInfoDtoStatus[keyof typeof EscrowInfoDtoStatus];


export const EscrowInfoDtoStatus = {
  pending: 'pending',
  locked: 'locked',
  released: 'released',
  refunded: 'refunded',
} as const;
