/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Free Go API
 * OpenAPI spec version: 1.0
 */

/**
 * @nullable
 */
export type LeaderboardEntryDtoLastName = { [key: string]: unknown } | null;
