/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Free Go API
 * OpenAPI spec version: 1.0
 */

export interface LeaderboardEntryDto {
  rank: number;
  first_name: string;
  /** @nullable */
  last_name?: string | null;
  /** @nullable */
  username?: string | null;
  referral_count: number;
}
