/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Free Go API
 * OpenAPI spec version: 1.0
 */

export interface MeResponseDto {
  id: number;
  telegram_id: string;
  first_name: string;
  /** @nullable */
  last_name?: string | null;
  /** @nullable */
  username?: string | null;
  /** @nullable */
  photo_url?: string | null;
  referral_code: string;
  referral_count: number;
  is_pro: boolean;
  /** @nullable */
  pro_until?: string | null;
  is_admin: boolean;
  created_at: string;
}
