/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Free Go API
 * OpenAPI spec version: 1.0
 */

export interface ProStatusResponseDto {
  is_active: boolean;
  /** @nullable */
  active_until?: string | null;
  total_slots: number;
  taken_slots: number;
  promo_ends_at: string;
  /** @nullable */
  pro_url?: string | null;
  /** How many days Pro is granted for when claimed */
  pro_days: number;
}
