/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */

export interface RegisterChannelDto {
  /** Telegram channel ID (numeric ID or @username) */
  telegramChannelId: string;
}
