/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */

export interface SubmitCreativeDto {
  /** Deal UUID */
  dealId: string;
  /** The ad text content to be posted */
  content: string;
}
