/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Free Go API
 * OpenAPI spec version: 1.0
 */
import type { ChannelDto } from './channelDto';

export interface SubscriptionStatusDto {
  subscribed: boolean;
  missing: ChannelDto[];
}
