/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */

export type TransitionDealDtoTargetStatus = typeof TransitionDealDtoTargetStatus[keyof typeof TransitionDealDtoTargetStatus];


export const TransitionDealDtoTargetStatus = {
  negotiation: 'negotiation',
  waitingPayment: 'waitingPayment',
  fundsLocked: 'fundsLocked',
  creativeSubmitted: 'creativeSubmitted',
  creativeApproved: 'creativeApproved',
  posted: 'posted',
  verified: 'verified',
  paidOut: 'paidOut',
  cancelled: 'cancelled',
  refunded: 'refunded',
} as const;
