/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */
import type { UpdateChannelManagerDtoRightsItem } from './updateChannelManagerDtoRightsItem';

export interface UpdateChannelManagerDto {
  /** Channel UUID */
  channelId?: string;
  /** Manager telegram user ID */
  userTelegramId?: string;
  rights?: UpdateChannelManagerDtoRightsItem[];
}
