/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */

export interface UpdateListingDto {
  /** Channel UUID */
  channelId?: string;
  /** Price in TON */
  priceTon?: number;
  /** Ad format description, e.g. "1/24 post", "story mention" */
  formatDescription?: string;
}
