/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */

export type UpdateChannelManagerDtoRightsItem = typeof UpdateChannelManagerDtoRightsItem[keyof typeof UpdateChannelManagerDtoRightsItem];


export const UpdateChannelManagerDtoRightsItem = {
  post: 'post',
  finance: 'finance',
  edit: 'edit',
} as const;
