/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */

export interface User {
  /** Telegram user ID */
  telegramId: string;
  createdAt: string;
  /** @nullable */
  username: string | null;
  /** @nullable */
  tonDepositAddress: string | null;
  /** @nullable */
  photoUrl: string | null;
  /** Available balance in nano TON */
  balanceNano: string;
}
