/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';
import type { WalletWithdrawalStatus } from './walletWithdrawalStatus';

export interface WalletWithdrawal {
  id: string;
  createdAt: string;
  updatedAt: string;
  userTelegramId: string;
  toAddress: string;
  /** Amount in nano TON */
  amountNano: string;
  status: WalletWithdrawalStatus;
  /** @nullable */
  txHash: string | null;
  /** @nullable */
  failureReason: string | null;
  user: User;
}
