/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */

export type WalletWithdrawalStatus = typeof WalletWithdrawalStatus[keyof typeof WalletWithdrawalStatus];


export const WalletWithdrawalStatus = {
  pending: 'pending',
  completed: 'completed',
  failed: 'failed',
} as const;
