/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */
import type { User } from './user';
import type { WalletLedgerType } from './walletLedgerType';

export interface WalletLedger {
  id: string;
  createdAt: string;
  userTelegramId: string;
  /** Signed amount in nano TON */
  amountNano: string;
  type: WalletLedgerType;
  /** @nullable */
  dealId: string | null;
  /** @nullable */
  withdrawalId: string | null;
  user: User;
}
