/**
 * Generated by orval v8.4.1 🍺
 * Do not edit manually.
 * Teleads
 * Telegram Ads Marketplace API
 * OpenAPI spec version: 1.0
 */

export type WalletLedgerType = typeof WalletLedgerType[keyof typeof WalletLedgerType];


export const WalletLedgerType = {
  dealPayoutCredit: 'dealPayoutCredit',
  withdrawalDebit: 'withdrawalDebit',
  withdrawalRollback: 'withdrawalRollback',
} as const;
